export const rebeccaProfileTranslations = {
  imagePath: "/leadership/r1.jpg",
  imagePathHover: "/leadership/r2.jpg",
  imageObjectPosition: "center 40%",
  imageObjectPositionHover: "center 18%",
  heroTag: { en: "Our Leadership", ko: "리더십" },
  heroTitle: { en: "Rebecca, PARK Ji Hyun", ko: "박지현 Rebecca" },
  heroSubtitle: { en: "HKICPA (Practising), CIA", ko: "HKICPA (Practising), CIA" },
  inBriefDescription: {
    en: "Rebecca is co-founder of Olive and Vine and is mainly responsible for the assurance service. She has numerous experience auditing small to medium sized companies based in Hong Kong, and also listed companies in Korea and Hong Kong. Her experience covers various industries including but not limited to retail, construction, trading, investment holding, cryptocurrencies, and more. Rebecca is highly self-driven, independent, and forward looking professional with diverse background. She has lived in Hong Kong for 15 years and previously lived in Singapore, China, Australia, and Korea. She understands different culture with the first hand experience she had interacting with people from different backgrounds.\n\nShe has devoted her study and career to audit and accounting. She has majored in accounting and finance and started her career at one of the top accounting firm, PwC. With the extensive exposure to the best resources and experience, she has moved on to develop her career as an engagement leader in past 4 years.\n\nRebecca is a true believer in principles. She believes that the impactful outcomes can only be achieved by the exercise of principles. She is strengthened by strong compassion, providing pragmatic solutions and devoted services to her clients.",
    ko: "박지현회계사는 올리브 앤 바인의 공동창업자이며 감사분야를 담당하고 있습니다. 한국과 홍콩상장사 업무를 다수 담당하였으며, 대기업뿐 아니라 중소기업, 그 중에서도 홍콩소재의 한국계 중소기업 감사담당자로 폭넓은 경험을 보유하고 있습니다.  소매업, 건설업, 무역, 지주회사, 가상화폐등 다양한 분야의 경험을 보유하고 있습니다. \n\n박지현회계사는 독립적이며 진취적인 사고를 하는 전문가로 국제적인 경험을 보유하고 있습니다. 15년이상 홍콩에 거주하여 현지사정을 깊이 이해하고 있으며 과거 싱가폴, 중국, 호주와 한국에서 학업 및 직업생활을 했습니다. 다양한 문화를 직접 경험한 것과 4개언어에 능통한것을 바탕으로 여러 문화권 사람과 쉽게 어울리며 업무를 진행할 수 있습니다. \n\n박지현회계사는 감사와 회계 분야에 집중하여 커리어와 학업을 쌓았습니다. 홍콩대학교에서 회계학을 졸업한 후 국제최고의 회계법인인 PwC에서 감사업무를 시작하였고, 그 후 홍콩의 일신회계법인에서 지난 4년간 감사담당회계사로 홍콩의 한국기업들과 직접적이고 현실적인 경험을 쌓았습니다. \n\n박지현회계사는 원칙을 중요시하며 깊은 공감을 통해 의미있는 결과물을 창출해내어 고객이 만족하는 서비스를 제공할 것입니다. ",
  },
  educationTitle: { en: "Education", ko: "학력" },
  educationDescription: {
    en: "University of Hong Kong, Bachelor of Business Administration in Accounting and Finance",
    ko: "홍콩대학교, 회계 및 금융 경영학사",
  },
  educationItems: {
    en: ["University of Hong Kong, Bachelor of Business Administration in Accounting and Finance"],
    ko: ["홍콩대학교, 회계 및 금융 경영학사"],
  },
  professionalCareersTitle: { en: "Professional careers", ko: "경력" },
  professionalCareersItems: {
    en: ["PwC HK, Assurance", "PwC Australia Sydney, Assurance", "IL Shin CPA Limited, Engagement leader"],
    ko: ["PwC 홍콩, Assurance", "PwC 호주 시드니, Assurance", "일신회계법인(IL Shin CPA Limited)"],
  },
  languageTitle: { en: "Language", ko: "언어" },
  languageItems: {
    en: ["Korean, English, Cantonese, Mandarin"],
    ko: ["한국어, 영어, 광둥어, 중국어"],
  },
  keyExperienceTitle: { en: "Key experience and expertise", ko: "핵심 경험 및 전문성" },
  keyExperienceItems: {
    en: [
      "Audit experience with diversified industries including trading, retail, investment holding, manufacturing, construction, crypto currencies, transmission network and more",
      "Multiple audit experience with consolidation, overseas subsidiaries/associates, joint operation/ventures, equity method",
      "Audit of various sized companies from small and medium sized clients to HKEX listed companies in Hong Kong",
      "Audit of Korean entities in Hong Kong including Samsung Electronics Hong Kong (from the initial year), LG electronics Hong Kong (in the initial year) and more",
      "Component audit of MNCs listed in Korea including KT&G, Hanjin, Lotte, LT Sambo, LX international, SK, Line, Neowiz, Kolon, SeAH, Taekwang",
      "Hong Kong IPO Project",
      "PCAOB component audit of a US listed company",
      "Regulatory audit and review of NSW transmission network entities in Australia",
    ],
    ko: [
      "무역, 소매업, 지주회사, 제조업, 건설업, 가상화폐, 송전업을 포함한 다양한 분야의 감사경험",
      "그룹사, 해외자회사 및 관계회사, 합작회사와 공동경영의 연결재무제표감사와 합산재무제표감사 및 지분법",
      "상장사주터 중소기업과 비영리법인까지 다양한 규모와 형태의 법인 감사경험",
      "한국대기업의 자회사 를 포함한 홍콩내 한국계법인 감사경험 (삼성전자 홍콩법인, LG전자 홍콩법인 감사) ",
      "한국 대기업 자회사 홍콩법인 감사 (KT&G, 한진, 롯데, LT삼보, LX인터내셔널, SK, 라인, 네오위즈, 코오롱, 세아상역, 태광 등) ",
      "홍콩 IPO 프로젝트",
      "미국상장사 홍콩자회사 PCAOB 감사",
      "호주 New South Wales 주 송전회사의 규정감사 (Regulatory audit) 와 외부감사",
    ],
  },
};
